In [33]:
import pandas as pd
import numpy as np
import random, time

In [34]:
def norm(dataset):
    for column_index in range(dataset.shape[1] - 1):
        max_val = dataset[column_index].max()
        min_val = dataset[column_index].min()

        dataset[column_index] = (dataset[column_index] - min_val) / (max_val - min_val)

In [35]:
def predict(w, x):
    scaled_x = np.dot(w, x)
    if scaled_x > 0:
        return 1
    else:
        return 0

# get accuracy, confusion matrices and rates
def train(dataset, split, error_threshold, alpha):
        
    #splitting into training and testing data
    group0 = dataset[dataset.iloc[:, 2] == 0]
    group1 = dataset[dataset.iloc[:, 2] == 1]
    sample_size = int(min(len(group0), len(group1)) * split)
    sampled_subset0 = group0.sample(n = sample_size, random_state = 42)
    sampled_subset1 = group1.sample(n = sample_size, random_state = 42)
    training = pd.concat([sampled_subset0, sampled_subset1])
    testing = dataset.drop(training.index)   
    
    
    
    #initialization stuff
    limit = 5000
    patterns = training.shape[0]
    w = [random.uniform(-0.5, 0.5) for _ in range(training.shape[1])]
    
    
    
    #training 
    i = 0
    error = patterns
    #while i is less than 5000 or it is not accurate enough
    while i < limit and error > error_threshold:
        #the error in this iteration of the neuron
        error = 0
        
        for row in range(patterns):
            x = training.iloc[row].values
            scaled_x = predict(w, x)
                
            #for total error sum[(out - desired)^2]. (-1)^2 = 1 and 1^2 = 1 so += 1 when they're different
            if x[2] != scaled_x:
                error += 1
                
            delta_weight = alpha * (x[2] - scaled_x)
            delta_weighted_x = x * delta_weight
            w = np.array(w) + np.array(delta_weighted_x)
        i += 1
    
    print(i)
    print(f"Total error in training is: {error}")
    
    
    
    #testing
    true_positive = false_positive = true_negative = false_negative = 0
    for row in range(testing.shape[0]):
        x = testing.iloc[row].values
        predicted = predict(w, x)
        true = x[2]
        
        if predicted == 1 and true == 1:
            true_positive += 1
        elif predicted == 1 and true == 0:
            false_positive += 1
        elif predicted == 0 and true == 1:
            false_negative += 1
        else:
            true_negative += 1
    
    accuracy = (true_positive + true_negative) / testing.shape[0]
    true_positive_rate = true_positive / (true_positive + false_positive)
    false_positive_rate = false_positive / (true_positive + false_positive)
    true_negative_rate = true_negative / (true_negative + false_negative)
    false_negative_rate = false_negative / (true_negative + false_negative)
    
    print(f"true positive: {true_positive}\nrate: {true_positive_rate}\n\n")
    print(f"false positive: {false_positive}\nrate: {false_positive_rate}\n\n")
    print(f"true negative: {true_negative}\nrate: {true_negative_rate}\n\n")
    print(f"false negative: {false_negative}\nrate: {false_negative_rate}\n\n")
    print(f"accuracy: {accuracy}")

    return w

In [36]:
#read the datasets
a = pd.read_csv("groupA.csv", header = None)
b = pd.read_csv("groupB.csv", header = None)
c = pd.read_csv("groupC.csv", header = None)



#convert to numeric
for col in a.columns:
    a[col] = a[col].apply(pd.to_numeric, errors = 'coerce')
    b[col] = b[col].apply(pd.to_numeric, errors = 'coerce')
    c[col] = c[col].apply(pd.to_numeric, errors = 'coerce')
    
    

#normalize the data
norm(a)
norm(b)
norm(c)










#soft activation
print(train(a, 3/4, 0.00001, 0.01))
print(train(a, 1/4, 0.00001, 0.01))

print(train(b, 3/4, 40, 0.01))
print(train(b, 1/4, 40, 0.01))

print(train(c, 3/4, 700, 0.01))
print(train(c, 1/4, 700, 0.01))





# #hard activation
# print(train(a, 3/4, 0.00001, 0.1))
# print(train(a, 1/4, 0.00001, 0.1))

# print(train(b, 3/4, 40, 0.1))
# print(train(b, 1/4, 40, 0.1))

# print(train(c, 3/4, 700, 0.1))
# print(train(c, 1/4, 700, 0.1))








# matplotlib stuff here? store the values of the weight, plot the data, draw the division line
# train() function can print the accuracy and confusion matrices
# maybe?

7
Total error in training is: 0
true positive: 500
rate: 1.0


false positive: 0
rate: 0.0


true negative: 500
rate: 1.0


false negative: 0
rate: 0.0


accuracy: 1.0
[-0.00437744 -0.00214415  0.01181294]
9
Total error in training is: 0
true positive: 1500
rate: 0.9986684420772304


false positive: 2
rate: 0.0013315579227696406


true negative: 1498
rate: 1.0


false negative: 0
rate: 0.0


accuracy: 0.9993333333333333
[-0.06759276  0.01011331  0.07228504]
1
Total error in training is: 13
true positive: 500
rate: 1.0


false positive: 0
rate: 0.0


true negative: 500
rate: 1.0


false negative: 0
rate: 0.0


accuracy: 1.0
[-0.26588062 -0.13443574  0.38665992]
1
Total error in training is: 8
true positive: 1500
rate: 0.9493670886075949


false positive: 80
rate: 0.05063291139240506


true negative: 1420
rate: 1.0


false negative: 0
rate: 0.0


accuracy: 0.9733333333333334
[-0.39856617  0.23326978  0.26784833]
1
Total error in training is: 47
true positive: 500
rate: 0.8431703204047217